version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
    links:
      - postgres_db:localhost
  postgres_db:
    image: "ngo:latest"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ngo
      POSTGRES_PASSWORD: postgres
